# Generated by Django 3.0.4 on 2020-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='facebook_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='twitter_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='website_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='youtube_url',
            field=models.URLField(),
        ),
    ]
